# Generated by Django 5.1 on 2024-11-29 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electerus_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='projects/gallery/')),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='gallery_images',
            field=models.ManyToManyField(blank=True, related_name='projects', to='electerus_app.galleryimage'),
        ),
    ]
