# Generated by Django 5.1 on 2024-11-29 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('electerus_app', '0002_galleryimage_project_gallery_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='gallery_images',
        ),
        migrations.DeleteModel(
            name='GalleryImage',
        ),
        migrations.DeleteModel(
            name='Project',
        ),
    ]
